GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjMyOTcxODc2LCJleHAiOjE2MzI5NzE4OTF9.1u56JMe_lZmDYp0XbGgxxKH_WkE6GWe4dlGoNuQovkk

###
DELETE http://localhost:4000/logout
Content-Type: application/json
{
  "token": 
}
###
POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjMyOTcyMTMwfQ.3sKCqCzdWYykJvPgif9Ud5mHY7xR27v_gWZi3rPp27U"
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}