GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzI4MTkxNTZ9.BzdS64HQFTu8d8mSkPmGgnxCtQAOw8dPTMqO-DgTO00

###

POST http://localhost:3000/login
Content-Type: application/application/json

{
  "username": "Kyle"
}